module.exports = {
	sondagem: [
		{ questionName: 'Datas', paramName: 'answer_date' },
		{ questionName: 'Notas - Média', paramName: 'media' },
		{ questionName: 'Como você avalia sua capacidade de definir objetivos claros a serem perseguidos?', paramName: 'objetivos_perseguidos' },
		{ questionName: 'Como você avalia sua capacidade de identificar as ações necessárias para atingir seus objetivos, organizando-as em um plano de ação viável ?', paramName: 'identificar_plano' },
		{ questionName: 'Como você avalia sua perseverança, isto é, sua capacidade de seguir seus planos até o fim?', paramName: 'plano_fim' },
		{ questionName: 'Como você avalia sua capacidade de perseguir objetivos com foco e comprometimento?', paramName: 'objetivos_foco' },
		{ questionName: 'Você costuma atingir os objetivos que traçou? (Dê uma nota de 1 a 10, sendo 1 se nunca consegue atingir os objetivos que traçou e 10 se sempre consegue)', paramName: 'costuma_atingir' },
		{ questionName: 'Como você avalia seu nível de consciência de seu verdadeiro potencial?', paramName: 'verdadeiro_potencial' },
		{ questionName: 'Como você avalia sua capacidade de identificar e superar bloqueios que te impedem de usar o seu potencial plenamente?', paramName: 'superar_bloqueios' },
		{ questionName: 'Como você avalia sua capacidade de organizar seu tempo de forma a priorizar o que é mais importante?', paramName: 'tempo_priorizar' },
		{ questionName: 'Como você avalia sua capacidade de equilibrar sua vida pessoal e profissional?', paramName: 'equilibrar_vida' },
		{ questionName: 'Como você avalia o seu grau de consciência de seu nível de estresse e de como ele afeta sua vida?', paramName: 'estresse_afeta' },
		{ questionName: 'Como você avalia o seu grau de consciência das causas de seu estresse?', paramName: 'estresse_causas' },
		{ questionName: 'Como você avalia o seu grau de conhecimento e sua capacidade de utilizar estratégias para o controle do estresse?', paramName: 'estresse_controle' },
		{ questionName: 'Como você avalia o seu grau de consciência das emoções que sente e de como elas influenciam o seu comportamento?', paramName: 'emocoes_comportamento' },
		{ questionName: 'Como você avalia sua capacidade de administrar suas emoções em momentos de pressão?', paramName: 'emocoes_pressao' },
		{ questionName: 'Como você avalia sua capacidade de identificar as emoções que as outras pessoas sentem e de como lidar com elas?', paramName: 'emocoes_outros' },
		{ questionName: 'Como você avalia sua satisfação com seus relacionamentos pessoais?', paramName: 'relacionamento_satisfacao' },
		{ questionName: 'Como você avalia sua capacidade de construir relacionamentos pessoais saudáveis e produtivos?', paramName: 'relacionamento_construir' },
		{ questionName: 'Como você avalia sua capacidade de identificar e resolver problemas que possam afetar os seus relacionamentos pessoais?', paramName: 'relacionamento_problemas' },
		{ questionName: 'Como você avalia sua satisfação com seus relacionamentos profissionais?', paramName: 'relacionamento_pro_satis' },
		{ questionName: 'Como você avalia sua capacidade de construir relacionamentos profissionais saudáveis e produtivos?', paramName: 'relacionamento_pro_const' },
		{ questionName: 'Como você avalia sua capacidade de identificar e resolver problemas que possam afetar os seus relacionamentos profissionais?', paramName: 'relacionamento_pro_prob' },
		{ questionName: 'Como você avalia sua capacidade de se comunicar com clareza e objetividade?', paramName: 'comunicar_clareza' },
		{ questionName: 'Como você avalia sua capacidade de se comunicar para obter apoios, administrar conflitos e atingir seus objetivos?', paramName: 'comunicar_apoio' },
		{ questionName: 'Como você avalia sua capacidade de se expressar de maneira segura e convicta ?', paramName: 'expressar_segura' },
		{ questionName: 'Como você avalia o seu grau de energia e motivação, tanto para realizar suas atividades diárias como para perseguir seus objetivos e superar as dificuldades?', paramName: 'energia_perseguir' },
		{ questionName: 'Como você avalia a sua capacidade de entender de forma clara e rápida a decisão que deve tomar?', paramName: 'entender_decisao' },
		{ questionName: 'Como você avalia sua capacidade de definir e analisar diferentes opções e cursos de ação, mesmo sob pressão?', paramName: 'analisar_pressao' },
		{ questionName: 'Como você avalia a sua capacidade de analisar as possíveis consequencias de sua decisão, antes de tomá-la?', paramName: 'decisao_consequencia' },
		{ questionName: 'Como você avalia o seu grau de clareza quanto a seus objetivos e necessidades de desenvolvimento pessoal?', paramName: 'objetivos_pessoal' },
		{ questionName: 'Como você avalia o grau de prioridade que você dá para o seu desenvolvimento pessoal?', paramName: 'prioridade_pessoal' },
		{ questionName: 'Como você avalia o seu grau de clareza quanto a seus objetivos e necessidades de desenvolvimento profissional?', paramName: 'prioridade_profissional' },
		{ questionName: 'Como você avalia o grau de prioridade que você dá para o seu desenvolvimento profissional?', paramName: 'grau_prioridade_pro' },
		{ questionName: 'Como você avalia o seu grau de satisfação com a sua situação financeira atual?', paramName: 'satisfacao_financeira' },
		{ questionName: 'Como você avalia sua capacidade de administrar o seu orçamento pessoal e familiar?', paramName: 'administrar_orcamento' },
		{ questionName: 'Como você avalia sua capacidade de identificar e reconhecer hábitos e comportamentos que produzem resultados negativos em sua vida?', paramName: 'habitos_negativos' },
		{ questionName: 'Como você avalia sua atuação para mudar os hábitos e comportamentos que produzem resultados negativos?', paramName: 'atuar_habitos' },
		{ questionName: 'Como você avalia sua confiança em sua capacidade e potencial?', paramName: 'confianca_capacidade' },
		{ questionName: 'Como você avalia o seu grau de satisfação consigo mesma?', paramName: 'satisfacao_consigo' },
		{ questionName: 'Como você avalia sua qualidade de vida atualmente?', paramName: 'qualidade_vida' },
		{ questionName: 'Como você avalia sua capacidade de agir concretamente para melhorar sua saúde física? (por exemplo, alimentação saudável, exercícios regulares, etc)', paramName: 'melhor_saude_fisica' },
		{ questionName: 'Como você avalia sua capacidade de agir concretamente para melhorar sua saúde psicológica ? (por exemplo fazer terapia, meditação, etc )', paramName: 'melhor_saude_psico' },
		{ questionName: 'Como você avalia sua disposição para exceder às expectativas que as pessoas tem em relação a seu trabalho? (seja realizando mais do que é pedido, seja realizando ações e propondo melhorias sem ser solicitada)', paramName: 'exceder_expectativas' },
		{ questionName: 'Como você avalia a sua capacidade de liderança?', paramName: 'capacidade_lideranca' },
		{ questionName: 'Como você avalia sua capacidade de agir rapidamente para resolver problemas?', paramName: 'agir_rapidamente' },
		{ questionName: 'Como você avalia a sua capacidade de separar quais problemas devem ser resolvidos por você e quais são de responsabilidade de outra pessoa?', paramName: 'separar_problemas' },
		{ questionName: 'Como você avalia sua capacidade de dar soluções definitivas a problemas, de forma que eles não ressurjam no futuro?', paramName: 'solucoes_definitivas' },
		{ questionName: 'Como você avalia o seu grau de conhecimento e sua capacidade de utilizar técnicas de resoluções de problemas no seu dia a dia?', paramName: 'conhecimento_resolucao' },
	],
	avaliacao360Pre: [
		{ questionName: 'Como você avalia a perseverança da pessoa, isto é, sua capacidade de seguir seus planos até o fim?', paramName: 'avalias1' },
		{ questionName: '', paramName: 'exemplo1' },
		{ questionName: '', paramName: 'melhora1' },
		{ questionName: 'Como você avalia a capacidade da pessoa de identificar e superar bloqueios que a impedem de usar o seu potencial plenamente?', paramName: 'avalias2' },
		{ questionName: '', paramName: 'exemplo2' },
		{ questionName: '', paramName: 'melhora2' },
		{ questionName: 'Como você avalia a capacidade da pessoa de organizar seu tempo de forma a priorizar o que é mais importante?', paramName: 'avalias3' },
		{ questionName: '', paramName: 'exemplo3' },
		{ questionName: '', paramName: 'melhora3' },
		{ questionName: 'Como você avalia a capacidade da pessoa de administrar suas emoções em momentos de pressão?', paramName: 'avalias4' },
		{ questionName: '', paramName: 'exemplo4' },
		{ questionName: '', paramName: 'melhora4' },
		{ questionName: 'Como você avalia a capacidade da pessoa de gerar influência e manter bons relacionamentos?', paramName: 'avalias5' },
		{ questionName: '', paramName: 'exemplo5' },
		{ questionName: '', paramName: 'melhora5' },
		{ questionName: 'Como você avalia a capacidade da pessoa de se expressar de maneira segura e convicta?', paramName: 'avalias6' },
		{ questionName: '', paramName: 'exemplo6' },
		{ questionName: '', paramName: 'melhora6' },
		{ questionName: 'Como você avalia a capacidade da pessoa de definir e analisar diferentes opções e cursos de ação, mesmo sob pressão?', paramName: 'avalias7' },
		{ questionName: '', paramName: 'exemplo7' },
		{ questionName: '', paramName: 'melhora7' },
		{ questionName: ' Como você avalia a confiança da pessoa em sua própria capacidade e potencial?', paramName: 'avalias8' },
		{ questionName: '', paramName: 'exemplo8' },
		{ questionName: '', paramName: 'melhora8' },
		{ questionName: 'Como você avalia a disposição que a pessoa tem para exceder às expectativas em relação ao seu trabalho?', paramName: 'avalias9' },
		{ questionName: '', paramName: 'exemplo9' },
		{ questionName: '', paramName: 'melhora9' },
		{ questionName: 'Como você avalia a capacidade da pessoa de agir rapidamente para resolver problemas?', paramName: 'avalias10' },
		{ questionName: '', paramName: 'exemplo10' },
		{ questionName: '', paramName: 'melhora10' },
	],
	avaliador360pos: [
		{ questionName: 'Como você avalia a perseverança da pessoa, isto é, sua capacidade de seguir seus planos até o fim?', paramName: 'avalias1' },
		{ questionName: '', paramName: 'exemplo1' },
		{ questionName: 'Como você avalia a capacidade da pessoa de identificar e superar bloqueios que a impedem de usar o seu potencial plenamente?', paramName: 'avalias2' },
		{ questionName: '', paramName: 'exemplo2' },
		{ questionName: 'Como você avalia a capacidade da pessoa de organizar seu tempo de forma a priorizar o que é mais importante?', paramName: 'avalias3' },
		{ questionName: '', paramName: 'exemplo3' },
		{ questionName: 'Como você avalia a capacidade da pessoa de administrar suas emoções em momentos de pressão?', paramName: 'avalias4' },
		{ questionName: '', paramName: 'exemplo4' },
		{ questionName: 'Como você avalia a capacidade da pessoa de gerar influência e manter bons relacionamentos?', paramName: 'avalias5' },
		{ questionName: '', paramName: 'exemplo5' },
		{ questionName: 'Como você avalia a capacidade da pessoa de se expressar de maneira segura e convicta?', paramName: 'avalias6' },
		{ questionName: '', paramName: 'exemplo6' },
		{ questionName: 'Como você avalia a capacidade da pessoa de definir e analisar diferentes opções e cursos de ação, mesmo sob pressão?', paramName: 'avalias7' },
		{ questionName: '', paramName: 'exemplo7' },
		{ questionName: ' Como você avalia a confiança da pessoa em sua própria capacidade e potencial?', paramName: 'avalias8' },
		{ questionName: '', paramName: 'exemplo8' },
		{ questionName: 'Como você avalia a disposição que a pessoa tem para exceder às expectativas em relação ao seu trabalho?', paramName: 'avalias9' },
		{ questionName: '', paramName: 'exemplo9' },
		{ questionName: 'Como você avalia a capacidade da pessoa de agir rapidamente para resolver problemas?', paramName: 'avalias10' },
		{ questionName: '', paramName: 'exemplo10' },
		{ questionName: '', paramName: 'houve_evolucao' },
		{ questionName: '', paramName: 'onde_evolucao' },
	],
};
