module.exports = {
	autoAvaliacao: [
		{ questionName: 'Reconhecer preconceito de gênero', paramName: 'preconceito_genero' },
		{ questionName: 'Tratar preconceitos inconscientes', paramName: 'preconceito_inconsciente' },
		{ questionName: 'Quebrar as barreiras', paramName: 'quebrar_barreiras' },
		{ questionName: 'Tratar da equidade', paramName: 'tratar_equidade' },
		{ questionName: 'Auto-confiança para desafios', paramName: 'autoconfiante_destaque' },
		{ questionName: 'Comportamento confiante', paramName: 'clareza_comportamentos' },
		{ questionName: 'Passos para conquistar', paramName: 'clareza_passos' },
		{ questionName: 'Capacidade de liderar', paramName: 'capacidade_lideranca' },
		{ questionName: 'Deseja posição de poder', paramName: 'deseja_poder' },
		{ questionName: 'Motivação para agir', paramName: 'motivada_agir' },
		{ questionName: 'Depende de você', paramName: 'depende_de_vc' },
	],
	avaliacao360: [
		{ questionName: 'Perseverança da pessoa', paramName: 'perseveranca' },
		{ questionName: 'Superação de bloqueios', paramName: 'superar_bloqueios' },
		{ questionName: 'Organização do Tempo', paramName: 'organizar_tempo' },
		{ questionName: 'Emoções sobre pressão', paramName: 'administrar_emocoes' },
		{ questionName: 'Gerar inluência', paramName: 'gerar_influencias' },
		{ questionName: 'Comunicação clara', paramName: 'comunicar_clareza' },
		{ questionName: 'Expressão segura', paramName: 'expressar_segura' },
		{ questionName: 'Energia e motivação', paramName: 'energia_motivacao' },
		{ questionName: 'Analisar situações', paramName: 'definir_analisar' },
		{ questionName: 'Desenvolvimento pessoal', paramName: 'desenvolvimento_pessoal' },
		{ questionName: 'Desenvolvimento profissional', paramName: 'desenvolvimento_proissional' },
		{ questionName: 'Auto-confiança', paramName: 'confianca_capacidade' },
		{ questionName: 'Exceder expectativas', paramName: 'exceder_expectativas' },
		{ questionName: 'Ação Rápida', paramName: 'agir_rapidamente' },
	],
};
