module.exports = {
	autoAvaliacao: [
		{ questionName: 'Reconhecer preconceito de gênero', paramName: 'preconceito_genero' },
		{ questionName: 'Tratar preconceitos inconscientes', paramName: 'preconceito_inconsciente' },
		{ questionName: 'Quebrar as barreiras', paramName: 'quebrar_barreiras' },
		{ questionName: 'Tratar da equidade', paramName: 'tratar_equidade' },
		{ questionName: 'Auto-confiança para desafios', paramName: 'autoconfiante_destaque' },
		{ questionName: 'Comportamento confiante', paramName: 'clareza_comportamentos' },
		{ questionName: 'Passos para conquistar', paramName: 'clareza_passos' },
		{ questionName: 'Capacidade de liderar', paramName: 'capacidade_lideranca' },
		{ questionName: 'Deseja posição de poder', paramName: 'deseja_poder' },
		{ questionName: 'Motivação para agir', paramName: 'motivada_agir' },
		{ questionName: 'Depende de você', paramName: 'depende_de_vc' },
	],
	avaliacao360Pre: [
		{ questionName: 'Como você avalia a perseverança da pessoa, isto é, sua capacidade de seguir seus planos até o fim?', paramName: 'avalias1' },
		{ questionName: '', paramName: 'exemplo1' },
		{ questionName: '', paramName: 'melhora1' },
		{ questionName: 'Como você avalia a capacidade da pessoa de identificar e superar bloqueios que a impedem de usar o seu potencial plenamente?', paramName: 'avalias2' },
		{ questionName: '', paramName: 'exemplo2' },
		{ questionName: '', paramName: 'melhora2' },
		{ questionName: 'Como você avalia a capacidade da pessoa de organizar seu tempo de forma a priorizar o que é mais importante?', paramName: 'avalias3' },
		{ questionName: '', paramName: 'exemplo3' },
		{ questionName: '', paramName: 'melhora3' },
		{ questionName: 'Como você avalia a capacidade da pessoa de administrar suas emoções em momentos de pressão?', paramName: 'avalias4' },
		{ questionName: '', paramName: 'exemplo4' },
		{ questionName: '', paramName: 'melhora4' },
		{ questionName: 'Como você avalia a capacidade da pessoa de gerar influência e manter bons relacionamentos?', paramName: 'avalias5' },
		{ questionName: '', paramName: 'exemplo5' },
		{ questionName: '', paramName: 'melhora5' },
		{ questionName: 'Como você avalia a capacidade da pessoa de se expressar de maneira segura e convicta?', paramName: 'avalias6' },
		{ questionName: '', paramName: 'exemplo6' },
		{ questionName: '', paramName: 'melhora6' },
		{ questionName: 'Como você avalia a capacidade da pessoa de definir e analisar diferentes opções e cursos de ação, mesmo sob pressão?', paramName: 'avalias7' },
		{ questionName: '', paramName: 'exemplo7' },
		{ questionName: '', paramName: 'melhora7' },
		{ questionName: ' Como você avalia a confiança da pessoa em sua própria capacidade e potencial?', paramName: 'avalias8' },
		{ questionName: '', paramName: 'exemplo8' },
		{ questionName: '', paramName: 'melhora8' },
		{ questionName: 'Como você avalia a disposição que a pessoa tem para exceder às expectativas em relação ao seu trabalho?', paramName: 'avalias9' },
		{ questionName: '', paramName: 'exemplo9' },
		{ questionName: '', paramName: 'melhora9' },
		{ questionName: 'Como você avalia a capacidade da pessoa de agir rapidamente para resolver problemas?', paramName: 'avalias10' },
		{ questionName: '', paramName: 'exemplo10' },
		{ questionName: '', paramName: 'melhora10' },
	],
	avaliador360pos: [
		{ questionName: 'Como você avalia a perseverança da pessoa, isto é, sua capacidade de seguir seus planos até o fim?', paramName: 'avalias1' },
		{ questionName: '', paramName: 'exemplo1' },
		{ questionName: 'Como você avalia a capacidade da pessoa de identificar e superar bloqueios que a impedem de usar o seu potencial plenamente?', paramName: 'avalias2' },
		{ questionName: '', paramName: 'exemplo2' },
		{ questionName: 'Como você avalia a capacidade da pessoa de organizar seu tempo de forma a priorizar o que é mais importante?', paramName: 'avalias3' },
		{ questionName: '', paramName: 'exemplo3' },
		{ questionName: 'Como você avalia a capacidade da pessoa de administrar suas emoções em momentos de pressão?', paramName: 'avalias4' },
		{ questionName: '', paramName: 'exemplo4' },
		{ questionName: 'Como você avalia a capacidade da pessoa de gerar influência e manter bons relacionamentos?', paramName: 'avalias5' },
		{ questionName: '', paramName: 'exemplo5' },
		{ questionName: 'Como você avalia a capacidade da pessoa de se expressar de maneira segura e convicta?', paramName: 'avalias6' },
		{ questionName: '', paramName: 'exemplo6' },
		{ questionName: 'Como você avalia a capacidade da pessoa de definir e analisar diferentes opções e cursos de ação, mesmo sob pressão?', paramName: 'avalias7' },
		{ questionName: '', paramName: 'exemplo7' },
		{ questionName: ' Como você avalia a confiança da pessoa em sua própria capacidade e potencial?', paramName: 'avalias8' },
		{ questionName: '', paramName: 'exemplo8' },
		{ questionName: 'Como você avalia a disposição que a pessoa tem para exceder às expectativas em relação ao seu trabalho?', paramName: 'avalias9' },
		{ questionName: '', paramName: 'exemplo9' },
		{ questionName: 'Como você avalia a capacidade da pessoa de agir rapidamente para resolver problemas?', paramName: 'avalias10' },
		{ questionName: '', paramName: 'exemplo10' },
		{ questionName: '', paramName: 'houve_evolucao' },
		{ questionName: '', paramName: 'onde_evolucao' },
	],
};
